# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-01 23:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_checkout_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='year',
            field=models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=50),
        ),
    ]
