# Generated by Django 2.1.4 on 2019-01-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190101_1819'),
    ]

    operations = [

    ]
