# Generated by Django 2.1.4 on 2019-01-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_checkout_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
