# Generated by Django 2.1.4 on 2019-01-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190101_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
