# Generated by Django 2.1.4 on 2019-01-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190101_2013'),
    ]

    operations = [

    ]
