# Generated by Django 2.1.4 on 2019-01-04 00:38

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190101_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='due_date',
            field=models.DateField(default=app.models.deadline),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
